Author: Cloudflight GmbH
Copyright: Copyright (c) Cloudflight GmbH
License: Apache2
ManifestType: defaultLocale
ManifestVersion: 1.1.0
Moniker: dockerinwsl
PackageIdentifier: Cloudflight.DockerInWSL
PackageLocale: en-US
PackageName: DockerInWSL
PackageUrl: https://github.com/cloudflightio/dockerinwsl
PackageVersion: 1.1.41.220125
Publisher: Cloudflight GmbH
PublisherSupportUrl: https://github.com/cloudflightio/dockerinwsl
PublisherUrl: https://cloudflight.io
ShortDescription: Using WSL2 to run a docker on windows (using official dind alpine image)
Tags:
- docker
- wsl2
